//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_adress
    {
        public Delivery_adress()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id_adress { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
