//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class basyuni_demoEntities0 : DbContext
    {
        public basyuni_demoEntities0()
            : base("name=basyuni_demoEntities0")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Delivery_adress> Delivery_adress { get; set; }
        public DbSet<Orders_clients> Orders_clients { get; set; }
        public DbSet<Orders_status> Orders_status { get; set; }
        public DbSet<Product_category> Product_category { get; set; }
        public DbSet<Product_delivery> Product_delivery { get; set; }
        public DbSet<Product_name> Product_name { get; set; }
        public DbSet<Product_producer> Product_producer { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Users_roles> Users_roles { get; set; }
        public DbSet<Order> Orders { get; set; }
    }
}
