//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public int order_number_id { get; set; }
        public string articule { get; set; }
        public int amount { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int delivery_point { get; set; }
        public Nullable<int> id_client_name { get; set; }
        public int code { get; set; }
        public int id_status { get; set; }
    
        public virtual Delivery_adress Delivery_adress { get; set; }
        public virtual Orders_clients Orders_clients { get; set; }
        public virtual Orders_status Orders_status { get; set; }
    }
}
