//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_status
    {
        public Orders_status()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id_status { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
