//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_delivery
    {
        public Product_delivery()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int id_delivery { get; set; }
        public string delivery_name { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
