//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int product_id { get; set; }
        public string articule { get; set; }
        public int id_name { get; set; }
        public string measurement { get; set; }
        public int price { get; set; }
        public int biggest_sale { get; set; }
        public int id_producer { get; set; }
        public int id_delivery { get; set; }
        public int id_category { get; set; }
        public int active_sale { get; set; }
        public int amount_instock { get; set; }
        public string description { get; set; }
        public string image { get; set; }
    
        public virtual Product_category Product_category { get; set; }
        public virtual Product_delivery Product_delivery { get; set; }
        public virtual Product_name Product_name { get; set; }
        public virtual Product_producer Product_producer { get; set; }
    }
}
