//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public int role_id { get; set; }
        public string user_name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Users_roles Users_roles { get; set; }
    }
}
