//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_roles
    {
        public Users_roles()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id_role { get; set; }
        public string role_name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
